# Generated by Django 3.1 on 2020-08-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaLune', '0003_auto_20200816_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adresa',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='prezime',
            field=models.CharField(default='', max_length=500),
        ),
    ]
