# Generated by Django 3.1 on 2020-08-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaLune', '0004_auto_20200816_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='broj_telefona',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='grad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='ime',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adresa',
            field=models.CharField(default='', max_length=250),
        ),
    ]
